# Configuration JWT
jwt.secret=mySecretKeyForMairieProject2024!@#$%^&*()
jwt.expiration=86400
jwt.refresh-expiration=604800

# Configuration Spring Boot - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mairie_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
